apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java
  name: java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java
    spec:
      containers:
      - image: shruthi4100/simplejavaapp
        name: simplejavaapp
        resources: {}
status: {}
