apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-06-25T02:39:06Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: nodejsapp
  name: nodejslb
  namespace: default
  resourceVersion: "4062"
  uid: fcf0847e-3d1f-48cc-adc6-4277e24f42ec
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.137.82
  clusterIPs:
  - 10.100.137.82
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30310
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodejsapp
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: afcf0847e3d1f48ccadc64277e24f42e-602388375.us-east-1.elb.amazonaws.com
